GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlem9zMjAwMSIsImlkIjoiNjc3MDJmNzM0NDk1NmI4YjUzM2ExOWQzIiwiaWF0IjoxNzM1NDEzNDc3fQ.O_E1TRJiIZAXR7JsWLVYKhK0ptnTHl0t3fpRmWTeIg0

{   
    "title": "awesome blog 6",
    "author": "Jeff Bezos",
    "url": "http://www.myawesomeblog.com",
    "likes": 2
}

###

DELETE http://localhost:3003/api/blogs/67704f4397b3dd192d57012c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlem9zMjAwMSIsImlkIjoiNjc3MDJmNzM0NDk1NmI4YjUzM2ExOWQzIiwiaWF0IjoxNzM1NDEzNDc3fQ.O_E1TRJiIZAXR7JsWLVYKhK0ptnTHl0t3fpRmWTeIg0

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "bezos2001",
    "name": "Jeff Bezoz",
    "password":"amazonrainforest"
}

###

POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "bezos2001",
    "password": "amazonrainforest"
}

