GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlem9zMjAwMSIsImlkIjoiNjc3MDJmNzM0NDk1NmI4YjUzM2ExOWQzIiwiaWF0IjoxNzM1NDExODcwfQ.U0sItc_hE7GuWS-ELhUo7vphcF_6HwUwZOaAhy127uE

{   
    "title": "awesome blog 5",
    "author": "Jeff Bezos",
    "url": "http://www.myawesomeblog.com",
    "likes": 2
}

###

DELETE http://localhost:3003/api/blogs/67704b406852dc34607b1ebf
Authorization: Bearer eyJhbGciOiybmFtZSI6ImJlem9zMjAwMSIsImlkIjoiNjc3MDJmNzM0NDk1NmI4YjUzM2ExOWQzIiwiaWF0IjoxNzM1NDExODcwfQ.U0sItc_hE7GuWS-ELhUo7vphcF_6HwUwZOaAhy127uE

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "bezos2001",
    "name": "Jeff Bezoz",
    "password":"amazonrainforest"
}

###

POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "bezos2001",
    "password": "amazonrainforest"
}

